# Generated by Django 3.2.18 on 2023-04-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.CharField(blank=True, max_length=250)),
                ('language_code', models.CharField(default='en', max_length=250)),
            ],
        ),
    ]
