# SSH_HOST
# --------Production------------
# SSH_USER
# SSH_KEY
# REPO_PATH
# --------dev------------
# SSH_USER_DEV
# SSH_KEY_DEV
# REPO_PATH_DEV

name: Deploy Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: To the moon  🚀 🌑 🌒 🌓 🌔 🌕 (dev)
      uses: appleboy/ssh-action@v0.1.8
      command_timeout: 40m
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER_DEV }}
        key: ${{ secrets.SSH_KEY_DEV }}
        script: |
          cd ${{ secrets.REPO_PATH_DEV }}
          git checkout dev
          git pull
          docker-compose build
          docker-compose up
