# SSH_HOST
# --------Production------------
# SSH_USER
# SSH_KEY
# REPO_PATH
# --------dev------------
# SSH_USER_DEV
# SSH_KEY_DEV
# REPO_PATH_DEV

name: Deploy Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: To the moon 🚀 🌑 🌒 🌓 🌔 🌕
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.REPO_PATH}}
          git pull
          docker-compose -f docker-compose-deploy.yml build
          docker-compose -f docker-compose-deploy.yml up -d
